# Form implementation generated from reading ui file 'Plantilla_pantalla_principal.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import test_rc  # Importa el archivo de recursos generado

class Ui_Pantalla_principal(object):
    def setupUi(self, Pantalla_principal):
        Pantalla_principal.setObjectName("Pantalla_principal")
        Pantalla_principal.resize(854, 530)
        Pantalla_principal.setMinimumSize(QtCore.QSize(0, 0))
        Pantalla_principal.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:1, x2:0.318, y2:0.688, stop:0 rgba(68, 95, 116, 255), stop:1 rgba(48, 123, 163, 255));}")
        self.centralwidget = QtWidgets.QWidget(parent=Pantalla_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuIzquierdo = QtWidgets.QFrame(parent=self.frame_2)
        self.menuIzquierdo.setMinimumSize(QtCore.QSize(200, 0))
        self.menuIzquierdo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.menuIzquierdo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menuIzquierdo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuIzquierdo.setObjectName("menuIzquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuIzquierdo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.menuIzquierdo)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btnMenu = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnMenu.setGeometry(QtCore.QRect(-1, -2, 201, 75))
        self.btnMenu.setMinimumSize(QtCore.QSize(1, 75))
        self.btnMenu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnMenu.setSizeIncrement(QtCore.QSize(0, 80))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMenu.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 13pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(30, 30))
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.menuIzquierdo)
        self.frame_6.setEnabled(True)
        self.frame_6.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_6.setSizeIncrement(QtCore.QSize(160, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.btnInicio = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnInicio.setGeometry(QtCore.QRect(0, 0, 200, 65))
        self.btnInicio.setMinimumSize(QtCore.QSize(1, 65))
        self.btnInicio.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnInicio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnInicio.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Inicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnInicio.setIcon(icon1)
        self.btnInicio.setIconSize(QtCore.QSize(30, 30))
        self.btnInicio.setObjectName("btnInicio")
        self.btnListaPendientes = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnListaPendientes.setGeometry(QtCore.QRect(0, 70, 200, 65))
        self.btnListaPendientes.setMinimumSize(QtCore.QSize(1, 65))
        self.btnListaPendientes.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnListaPendientes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnListaPendientes.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Lista de pendientes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnListaPendientes.setIcon(icon2)
        self.btnListaPendientes.setIconSize(QtCore.QSize(30, 30))
        self.btnListaPendientes.setObjectName("btnListaPendientes")
        self.btnPomodoro = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnPomodoro.setGeometry(QtCore.QRect(0, 195, 200, 65))
        self.btnPomodoro.setMinimumSize(QtCore.QSize(1, 65))
        self.btnPomodoro.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnPomodoro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPomodoro.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icoco pomodoro.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPomodoro.setIcon(icon3)
        self.btnPomodoro.setIconSize(QtCore.QSize(30, 30))
        self.btnPomodoro.setObjectName("btnPomodoro")
        self.btnCalendario = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnCalendario.setGeometry(QtCore.QRect(0, 130, 200, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCalendario.sizePolicy().hasHeightForWidth())
        self.btnCalendario.setSizePolicy(sizePolicy)
        self.btnCalendario.setMinimumSize(QtCore.QSize(1, 65))
        self.btnCalendario.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnCalendario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCalendario.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Calendario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCalendario.setIcon(icon4)
        self.btnCalendario.setIconSize(QtCore.QSize(30, 30))
        self.btnCalendario.setObjectName("btnCalendario")
        self.btnCerrarSesion = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnCerrarSesion.setGeometry(QtCore.QRect(0, 380, 200, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCerrarSesion.sizePolicy().hasHeightForWidth())
        self.btnCerrarSesion.setSizePolicy(sizePolicy)
        self.btnCerrarSesion.setMinimumSize(QtCore.QSize(1, 65))
        self.btnCerrarSesion.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnCerrarSesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCerrarSesion.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCerrarSesion.setIcon(icon5)
        self.btnCerrarSesion.setIconSize(QtCore.QSize(30, 30))
        self.btnCerrarSesion.setObjectName("btnCerrarSesion")
        self.btnEstadisticas = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnEstadisticas.setGeometry(QtCore.QRect(0, 260, 200, 65))
        self.btnEstadisticas.setMinimumSize(QtCore.QSize(1, 65))
        self.btnEstadisticas.setMaximumSize(QtCore.QSize(16777215, 65))
        self.btnEstadisticas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnEstadisticas.setStyleSheet("QPushButton{\n"
"border:none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(43, 75, 93);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Estadisticas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEstadisticas.setIcon(icon6)
        self.btnEstadisticas.setIconSize(QtCore.QSize(30, 30))
        self.btnEstadisticas.setObjectName("btnEstadisticas")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.menuIzquierdo)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setKerning(False)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton.setGeometry(QtCore.QRect(590, 20, 40, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: transparent;\n"
"")
        self.pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Usuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon7)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 30, 35, 35))
        self.pushButton_2.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: transparent;")
        self.pushButton_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Notificaciones.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 30, 35, 35))
        self.pushButton_3.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_3.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: transparent;")
        self.pushButton_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono Ajustes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon9)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 30, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_7)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 291, 21))
        self.lineEdit.setStyleSheet("font: 9pt \"Cascadia Code\";\n"
"border-radius:10px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 181, 16))
        self.label_5.setStyleSheet("font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(320, 30, 31, 16))
        self.label_6.setStyleSheet("font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(430, 30, 41, 16))
        self.label_7.setStyleSheet("font: 700 10pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.menuDerecho = QtWidgets.QFrame(parent=self.frame_4)
        self.menuDerecho.setMaximumSize(QtCore.QSize(16777215, 400))
        self.menuDerecho.setStyleSheet("QWidget#menuDerecho{background-color: qradialgradient(spread:pad, cx:0.710227, cy:0.369, radius:1.07, fx:0.716364, fy:0.386, stop:0 rgba(26, 26, 26, 255), stop:1 rgba(47, 148, 255, 255));}")
        self.menuDerecho.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menuDerecho.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuDerecho.setObjectName("menuDerecho")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.menuDerecho)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.paginas = QtWidgets.QStackedWidget(parent=self.menuDerecho)
        self.paginas.setEnabled(True)
        self.paginas.setMaximumSize(QtCore.QSize(650, 400))
        self.paginas.setStyleSheet("background-color: transparent;")
        self.paginas.setObjectName("paginas")
        self.Estadisticas = QtWidgets.QWidget()
        self.Estadisticas.setObjectName("Estadisticas")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Estadisticas)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_12 = QtWidgets.QFrame(parent=self.Estadisticas)
        self.frame_12.setMaximumSize(QtCore.QSize(700, 400))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 230))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_16.setContentsMargins(9, -1, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_25)
        self.label_22.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_22.setSizeIncrement(QtCore.QSize(100, 0))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Captura estadisticas estado de las tareas.jpeg"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_16.addWidget(self.label_22)
        self.horizontalLayout_3.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_23)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_26)
        self.label_23.setGeometry(QtCore.QRect(0, -10, 321, 201))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("Captura tareas 2, progreso atrasadas.jpeg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.frame_26)
        self.verticalLayout_15.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_24.setMaximumSize(QtCore.QSize(700, 500))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_24 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_24.setMaximumSize(QtCore.QSize(650, 16777215))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/prefijoNuevo/Captura estaditicas de progreso.jpeg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_17.addWidget(self.label_24)
        self.verticalLayout_15.addWidget(self.frame_24)
        self.gridLayout_4.addWidget(self.frame_12, 0, 0, 1, 1)
        self.paginas.addWidget(self.Estadisticas)
        self.Lista_pendientes = QtWidgets.QWidget()
        self.Lista_pendientes.setObjectName("Lista_pendientes")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Lista_pendientes)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_21 = QtWidgets.QFrame(parent=self.Lista_pendientes)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_21)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 171, 22))
        self.label_18.setStyleSheet("font: 700 14pt \"Cascadia Code\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_21)
        self.pushButton_6.setGeometry(QtCore.QRect(580, 30, 41, 31))
        self.pushButton_6.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/prefijoNuevo/Icono ajustes 2.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon10)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_6.addWidget(self.frame_21)
        self.frame_19 = QtWidgets.QFrame(parent=self.Lista_pendientes)
        self.frame_19.setMaximumSize(QtCore.QSize(500, 445))
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
