# Form implementation generated from reading ui file '.\sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import archivo_rc


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(692, 491)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        Principal.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuDerecho = QtWidgets.QFrame(parent=self.frame_2)
        self.menuDerecho.setMinimumSize(QtCore.QSize(180, 0))
        self.menuDerecho.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuDerecho.setStyleSheet("QFrame{\n"
"background: #50549c;\n"
"\n"
"}")
        self.menuDerecho.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menuDerecho.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuDerecho.setObjectName("menuDerecho")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuDerecho)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(parent=self.menuDerecho)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btnMenu = QtWidgets.QPushButton(parent=self.frame_5)
        self.btnMenu.setGeometry(QtCore.QRect(0, 0, 180, 50))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnMenu.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}")
        self.btnMenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(30, 30))
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.menuDerecho)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.btnPrincipal = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnPrincipal.setGeometry(QtCore.QRect(0, 10, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btnPrincipal.setFont(font)
        self.btnPrincipal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPrincipal.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #40457c;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono inicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPrincipal.setIcon(icon1)
        self.btnPrincipal.setIconSize(QtCore.QSize(30, 30))
        self.btnPrincipal.setObjectName("btnPrincipal")
        self.btnListaPendientes = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnListaPendientes.setGeometry(QtCore.QRect(0, 70, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btnListaPendientes.setFont(font)
        self.btnListaPendientes.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnListaPendientes.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #40457c;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono lista de pendientes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnListaPendientes.setIcon(icon2)
        self.btnListaPendientes.setIconSize(QtCore.QSize(30, 30))
        self.btnListaPendientes.setObjectName("btnListaPendientes")
        self.btnCalendario = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnCalendario.setGeometry(QtCore.QRect(0, 130, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btnCalendario.setFont(font)
        self.btnCalendario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCalendario.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #40457c;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono calendario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCalendario.setIcon(icon3)
        self.btnCalendario.setIconSize(QtCore.QSize(30, 30))
        self.btnCalendario.setObjectName("btnCalendario")
        self.btnPomodoro = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnPomodoro.setGeometry(QtCore.QRect(-10, 190, 191, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        self.btnPomodoro.setFont(font)
        self.btnPomodoro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnPomodoro.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #40457c;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono Pomodoro.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPomodoro.setIcon(icon4)
        self.btnPomodoro.setIconSize(QtCore.QSize(70, 31))
        self.btnPomodoro.setObjectName("btnPomodoro")
        self.btnSalir = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnSalir.setGeometry(QtCore.QRect(0, 560, 180, 50))
        self.btnSalir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnSalir.setStyleSheet("QPushButton{\n"
"border: none;\n"
"background: transparent;\n"
"color: #fff;\n"
"padding: 10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #40457c;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Icono Salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalir.setIcon(icon5)
        self.btnSalir.setIconSize(QtCore.QSize(30, 30))
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.menuDerecho)
        self.menuIzquierdo = QtWidgets.QFrame(parent=self.frame_2)
        self.menuIzquierdo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.menuIzquierdo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menuIzquierdo.setObjectName("menuIzquierdo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menuIzquierdo)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paginas = QtWidgets.QStackedWidget(parent=self.menuIzquierdo)
        self.paginas.setObjectName("paginas")
        self.principal = QtWidgets.QWidget()
        self.principal.setStyleSheet("QFrame{\n"
"background: #21214a;\n"
"\n"
"}")
        self.principal.setObjectName("principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.principal)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.principal)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"text:#fff;\n"
"\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.paginas.addWidget(self.principal)
        self.listaPendientes = QtWidgets.QWidget()
        self.listaPendientes.setStyleSheet("QFrame{\n"
"background: #21214a;\n"
"\n"
"}")
        self.listaPendientes.setObjectName("listaPendientes")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.listaPendientes)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(parent=self.listaPendientes)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QFrame{\n"
"text:#fff;\n"
"\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.paginas.addWidget(self.listaPendientes)
        self.calendario = QtWidgets.QWidget()
        self.calendario.setStyleSheet("QFrame{\n"
"background: #21214a;\n"
"\n"
"}")
        self.calendario.setObjectName("calendario")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.calendario)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.calendario)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.paginas.addWidget(self.calendario)
        self.pomodoro = QtWidgets.QWidget()
        self.pomodoro.setObjectName("pomodoro")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pomodoro)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.pomodoro)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QFrame{\n"
"background: #21214a;\n"
"\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.paginas.addWidget(self.pomodoro)
        self.verticalLayout_3.addWidget(self.paginas)
        self.horizontalLayout_2.addWidget(self.menuIzquierdo)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        Principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Principal)
        self.paginas.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Menu principal"))
        self.btnPrincipal.setText(_translate("Principal", "  Inicio"))
        self.btnListaPendientes.setText(_translate("Principal", "  Lista de pendientes"))
        self.btnCalendario.setText(_translate("Principal", "  Calendario"))
        self.btnPomodoro.setText(_translate("Principal", "Pomodoro"))
        self.btnSalir.setText(_translate("Principal", "  Salir"))
        self.label.setText(_translate("Principal", "Principal"))
        self.label_2.setText(_translate("Principal", "Lista de pendientes"))
        self.label_3.setText(_translate("Principal", "Calendario"))
        self.label_4.setText(_translate("Principal", "Pomodoro"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec())
